### ISSUE TITLE
Change MOTD from "Lifeboat Network" to my server

### ISSUE THREAD

**Issue by XDqrkneZ** [Hydreon/Steadfast2#250]
Title says it all :D

**Comment by junkdude** [comment]
xd

**Comment by XDqrkneZ** [comment]
Lol?

**Comment by dktapps** [comment]
maybe you could even learn to read the [README.md](https://github.com/Hydreon/Steadfast2#getting-started)...

**Comment by XDqrkneZ** [comment]
I did lol, that doesn't help anything...

**Comment by tigerza117** [comment]
Steadfast is a project for backporting new Minecraft: Pocket Edition changes to older Pocketmine versions for better stability and performance, while retaining as many features from the new versions as possible. It's currently in production on Lifeboat Survival Games' main servers.

Things you might want to change before building:

Saving the server.log is disabled because it takes a lot of time to write to disk
The default MOTD for responding to MCPE server list queries is set in RaklibInterface (is currently set to Lifeboat Network)
Known bugs:

Things you'll want to change on your plugins:

Players don't fall out of the world naturally, you'll want to handle PlayerMoveEvent as needed to kill them

pls Read WTF

**Comment by XDqrkneZ** [comment]
k
